attach(VAPopulation)
summary(VAPopulation)
plot(VAPopulation$Year, VAPopulation$Population, xlab = "Year", ylab = "Population",  main = "Virginia Population Growth", type = 'o', col = "Blue")
abline(lm(Population ~Year, data = VAPopulation))
fit = lm (Year~Population, VAPopulation)
summary(fit)
coef(summary(fit))
predict(fit)
year2022 <- data.frame(Year = 2022)
predict(fit, year2022)
fit = lm(Population~Year, VAPopulation)
summary(fit)
vasum <- lm(Year~Population, VAPopulation)
summary(vasum)
predict(vasum)
newyear <- data.frame((Year = 2023))
predict(fit, newyear)
Newyear2022 <- data.frame((Year = 2022))
predict(fit, Newyear2022)
